import csv
import random

random.seed(42)

# Each entry: (base_nps, comment, insight, categoria)
# Some comments have {v} placeholders replaced by random choices at generation time

def sample(options):
    return random.choice(options)

# Templates lists with (nps, comment_template, insight, categoria, vars_dict)
# vars_dict maps placeholder -> list of options
TEMPLATES = []

# =============================================================================
# PRODUCTOS
# =============================================================================
TEMPLATES += [
    # --- HIPOTECA positivo ---
    (10, "La hipoteca a tipo fijo que firmé tiene unas condiciones inmejorables: sin comisión de apertura, sin penalización por amortizaciones anticipadas y con un tipo del {rate}%. Comparé con {n} bancos y este fue claramente el más competitivo. El proceso fue transparente de principio a fin.", "Satisfacción con condiciones competitivas de hipoteca fija", "Productos", {"rate": ["2.75","2.8","2.9","3.0","3.1"], "n": ["cuatro","cinco","seis","tres"]}),
    (9, "El proceso de firma de la hipoteca fue ágil y sin sorpresas. Me asignaron un gestor exclusivo que me acompañó en cada paso. Las condiciones acordadas al inicio fueron exactamente las que firmé. Después de {n} años siendo cliente, es la mejor decisión financiera que he tomado con este banco.", "Proceso hipotecario ágil y transparente sin cambios en condiciones", "Productos", {"n": ["cinco","seis","siete","ocho","diez"]}),
    (9, "Contraté la hipoteca verde porque la vivienda tiene certificado energético A y me aplicaron un diferencial {n} puntos básicos menor. El ahorro a largo plazo es considerable. Además, el banco planta un árbol por cada hipoteca verde contratada. Un producto bien diseñado con impacto real.", "Satisfacción con hipoteca verde y beneficio por eficiencia energética", "Productos", {"n": ["diez","quince","veinte","veinticinco"]}),
    # --- HIPOTECA negativo ---
    (2, "El proceso de solicitud de la hipoteca fue un desastre total. Me pidieron la misma documentación {n} veces porque la perdían. Tardaron {m} meses en darme respuesta. Cuando por fin aprobaron la hipoteca habían cambiado las condiciones iniciales. Perdí la reserva del piso por su ineficiencia.", "Proceso hipotecario caótico con cambio de condiciones y documentación perdida", "Productos", {"n": ["tres","cuatro","dos"], "m": ["cinco","seis","cuatro","siete"]}),
    (1, "Me prometieron un tipo fijo del {rate}% y al firmar era el {rate2}%. Nadie me avisó del cambio. Cuando reclamé me dijeron que había sido un error administrativo y que ya no podían modificarlo. Firmé bajo presión porque ya tenía fecha de notaría. Me siento completamente engañado.", "Modificación de tipo hipotecario sin previo aviso al momento de la firma", "Productos", {"rate": ["2.9","3.0","3.1"], "rate2": ["3.2","3.3","3.4","3.5"]}),
    (3, "La hipoteca variable me está destrozando con la subida del Euríbor. Cuando la contraté me explicaron muy poco los riesgos de la variabilidad. No me ofrecieron alternativa fija ni me informaron de la posibilidad de novación. Me siento desinformado en el momento más importante de mi vida financiera.", "Falta de información sobre riesgo de hipoteca variable al momento de la contratación", "Productos", {}),
    # --- PRÉSTAMO PERSONAL positivo ---
    (9, "El préstamo personal se resolvió en menos de {n} horas desde la solicitud online. Las condiciones eran exactamente las del simulador. Sin seguros vinculados obligatorios y con posibilidad de amortización anticipada sin coste. Para una urgencia económica es la solución perfecta.", "Préstamo personal aprobado en tiempo récord sin condiciones abusivas", "Productos", {"n": ["24","36","48"]}),
    (8, "Pedí un préstamo personal de {amount} euros para reformar la cocina y el proceso fue completamente digital. En {n} minutos tuve la aprobación y el dinero en cuenta al día siguiente. El tipo fue competitivo y sin letra pequeña. Muy satisfecho con la agilidad y transparencia.", "Proceso digital ágil y transparente en préstamo personal para reforma", "Productos", {"amount": ["5.000","8.000","10.000","12.000"], "n": ["diez","quince","veinte"]}),
    # --- PRÉSTAMO PERSONAL negativo ---
    (2, "El tipo de interés del préstamo personal que me ofrecieron era del {rate}% TAE. Para un cliente con buen historial crediticio es completamente injustificado. Otros bancos online me ofrecían la mitad. Cuando intenté negociarlo me dijeron que era la tarifa estándar sin excepciones.", "Tipo de interés del préstamo personal no competitivo ni negociable", "Productos", {"rate": ["17","18","19","16"]}),
    (3, "Cuando quise cancelar el préstamo personal anticipadamente me cobraron una penalización del {rate}% sobre el capital pendiente. Esto no me lo explicaron al contratar. Lo descubrí en un anexo de {n} páginas del contrato. Me costó más cancelar que terminar de pagar los plazos.", "Penalización por cancelación anticipada de préstamo no informada al contratar", "Productos", {"rate": ["3","4","3.5"], "n": ["cuarenta","cincuenta","treinta y cinco"]}),
    # --- TARJETA DE CRÉDITO positivo ---
    (10, "La tarjeta premium tiene acceso a {n} salas VIP en aeropuertos de todo el mundo, seguro de viaje completo y cashback del {rate}% en todas las compras. Con los beneficios que uso mensualmente la cuota se paga sola. Es el mejor producto financiero que he contratado.", "Alta satisfacción con beneficios completos de tarjeta premium", "Productos", {"n": ["mil","mil doscientas","novecientas"], "rate": ["2","2.5","3"]}),
    (8, "La tarjeta de crédito funciona perfectamente en el extranjero sin comisión por cambio de divisa. La puedo congelar y descongelar desde la app en segundos. El límite es adecuado a mis necesidades y puedo ampliarlo de forma temporal. Una tarjeta sin complicaciones ni sorpresas.", "Tarjeta de crédito sin comisiones por divisa y gestión ágil desde app", "Productos", {}),
    (9, "El programa de puntos de la tarjeta es muy generoso: {n} puntos por cada euro gastado y se pueden canjear por viajes, electrodomésticos o descuentos en compras. Ya he canjeado {m} puntos este año. Sin fecha de caducidad de los puntos. Un programa de fidelización bien diseñado.", "Satisfacción con programa de puntos generoso y sin caducidad", "Productos", {"n": ["dos","tres","cuatro"], "m": ["veinte mil","treinta mil","cincuenta mil"]}),
    # --- TARJETA DE CRÉDITO negativo ---
    (4, "Mi tarjeta de crédito tiene un límite de {amount} euros que no me suben desde hace {n} años aunque lo solicito cada seis meses. Con ese límite no puedo hacer reservas de hotel ni alquilar coches en el extranjero. Es un producto completamente inútil para mis necesidades actuales.", "Límite de crédito insuficiente sin posibilidad de ampliación tras múltiples solicitudes", "Productos", {"amount": ["500","600","800","1.000"], "n": ["dos","tres","cuatro"]}),
    (2, "Me cobraron intereses de demora del {rate}% por retrasar el pago {n} días. Un porcentaje abusivo que no me explicaron al contratar la tarjeta. Además lo aplicaron sobre el total de la deuda y no solo sobre el importe vencido. Una práctica financiera que roza la usura.", "Intereses de demora abusivos aplicados incorrectamente en tarjeta de crédito", "Productos", {"rate": ["26","28","24","30"], "n": ["tres","cuatro","cinco"]}),
    # --- TARJETA DÉBITO ---
    (9, "La tarjeta de débito funciona perfectamente en {n} países sin comisión. Tengo notificaciones instantáneas de cada pago, puedo bloquearla desde la app en segundos y gestionar el límite diario yo mismo. Es la tarjeta más completa que he tenido en todos mis años como cliente bancario.", "Tarjeta débito internacional completa con control total desde app", "Productos", {"n": ["cuarenta","cincuenta","sesenta"]}),
    (7, "La tarjeta débito contactless funciona en todos los comercios y en el transporte público. Las notificaciones son instantáneas y me ayudan a controlar el gasto diario. El único punto de mejora sería poder generar números de tarjeta virtuales para compras online.", "Satisfacción con tarjeta débito contactless con sugerencia de mejora", "Productos", {}),
    # --- CUENTA NÓMINA ---
    (10, "La cuenta nómina no tiene ninguna comisión con solo domiciliar la nómina. Incluye seguro de accidentes, descuento del {rate}% en la hipoteca y tarjeta sin cuota anual. El conjunto de beneficios supera con creces lo que me cobrarían en otros bancos por servicios equivalentes.", "Cuenta nómina con amplio paquete de beneficios por vinculación", "Productos", {"rate": ["0.2","0.25","0.3","0.15"]}),
    (8, "La cuenta nómina tiene condiciones muy buenas: sin comisiones, transferencias gratuitas y descuentos en seguros. Tardé {n} minutos en abrirla completamente online. El único punto negativo es que el seguro de accidentes tiene una cobertura algo limitada pero en general es un excelente producto.", "Satisfacción con cuenta nómina digital con proceso de apertura ágil", "Productos", {"n": ["diez","quince","veinte"]}),
    (3, "La cuenta nómina que me ofrecieron tiene tantas condiciones de vinculación que es imposible cumplirlas todas: nómina mínima de {amount} euros, {n} recibos domiciliados, tarjeta de crédito activa y seguro contratado. Si no cumples todo te cobran comisión. Es una trampa para cobrar comisiones camuflada.", "Condiciones de exención en cuenta nómina imposibles de cumplir para la mayoría", "Productos", {"amount": ["1.800","2.000","1.500","2.500"], "n": ["tres","cuatro","cinco"]}),
    # --- CUENTA AHORRO ---
    (9, "La cuenta de ahorro remunerada da un {rate}% anual sobre el saldo. Los intereses se abonan mensualmente y puedo retirar el dinero en cualquier momento sin penalización. Sin vinculaciones obligatorias. Es la mejor opción de ahorro líquido que he encontrado en la banca tradicional.", "Satisfacción con cuenta ahorro remunerada líquida sin condiciones", "Productos", {"rate": ["2.5","3","2","2.75","3.5"]}),
    (2, "La cuenta de ahorro ofrece un {rate}% de interés anual. Con la inflación actual eso significa perder poder adquisitivo cada año. Hay opciones en el mercado que ofrecen {rate2}% sin vinculación alguna. Mantener dinero aquí es claramente la peor decisión financiera posible para el ahorro.", "Rentabilidad de cuenta ahorro muy por debajo de alternativas del mercado", "Productos", {"rate": ["0.01","0.02","0.05"], "rate2": ["3","3.5","4","2.5"]}),
    # --- PLAN DE PENSIONES ---
    (10, "El plan de pensiones supera todas mis expectativas. La rentabilidad anual ha sido superior al {rate}% en los últimos tres años. Puedo cambiar el perfil de riesgo sin penalización y las comisiones de gestión son de las más bajas del sector. El mejor producto de ahorro a largo plazo que conozco.", "Alta rentabilidad y bajas comisiones en plan de pensiones", "Productos", {"rate": ["7","8","9","10"]}),
    (8, "El plan de pensiones permite aportaciones desde {amount} euros al mes y puedo aumentarlas o reducirlas cuando quiero. La variedad de perfiles de inversión es amplia. Los informes periódicos son claros y detallados. Para la jubilación es la opción más completa que he encontrado.", "Satisfacción con flexibilidad y transparencia en plan de pensiones", "Productos", {"amount": ["30","50","25","40"]}),
    (3, "El plan de pensiones que me vendieron tiene unas comisiones de gestión del {rate}% anual. Con esa carga es casi imposible obtener rentabilidad real. Además solo tienen {n} perfiles de inversión sin posibilidad de personalización. La oferta de planes del banco es claramente mejorable.", "Comisiones altas y escasa variedad en plan de pensiones del banco", "Productos", {"rate": ["1.8","2","1.5","2.2"], "n": ["tres","cuatro","dos"]}),
    # --- FONDO DE INVERSIÓN ---
    (9, "Los fondos indexados que ofrece el banco tienen comisiones de gestión del {rate}% y réplica fiel al índice. Puedo invertir desde {amount} euros mensuales de forma automatizada. Es una forma cómoda de acceder a los mercados globales sin gestión activa. Muy satisfecho con la oferta.", "Satisfacción con oferta de fondos indexados de bajo coste", "Productos", {"rate": ["0.15","0.2","0.1","0.25"], "amount": ["30","50","100","20"]}),
    (2, "El fondo de inversión activo que me recomendaron ha perdido un {rate}% en dos años mientras el índice de referencia subía. Las comisiones de gestión superan el {fee}% anual. Me siento engañado por un producto que prometía rendimientos superiores al mercado y no ha cumplido.", "Pérdidas en fondo activo con comisiones altas sin justificación de rendimiento", "Productos", {"rate": ["12","15","10","8"], "fee": ["2","2.2","1.8","1.5"]}),
    # --- SEGURO DE HOGAR ---
    (9, "El seguro de hogar del banco tiene una cobertura excelente: daños por agua, robo, responsabilidad civil y asistencia 24 horas. El precio es competitivo. Cuando tuve una fuga de agua me enviaron un técnico en menos de {n} horas y cubrieron todos los gastos sin discusión.", "Satisfacción con cobertura y rapidez de respuesta del seguro de hogar", "Productos", {"n": ["dos","tres","cuatro"]}),
    (4, "El seguro de hogar tiene un sinfín de exclusiones que no me explicaron al contratarlo. Cuando intenté reclamar por una inundación me denegaron la cobertura por un tecnicismo. Además el precio sube cada año un {rate}% sin mejora aparente en las condiciones. Completamente decepcionante.", "Exclusiones ocultas en seguro de hogar y aumento de precio sin mejora", "Productos", {"rate": ["8","10","12","15"]}),
    # --- SEGURO DE VIDA ---
    (1, "El seguro de vida vinculado a la hipoteca tiene unas condiciones abusivas. Me cobran {amount} euros al mes por una cobertura que apenas protege el {rate}% de la deuda. Cuando quise cancelarlo me dijeron que tenía penalización de {pen} años de primas. Me siento completamente atrapado.", "Seguro de vida vinculado a hipoteca con condiciones abusivas y cancelación penalizada", "Productos", {"amount": ["80","100","120","90"], "rate": ["50","60","70"], "pen": ["dos","tres"]}),
    (8, "El seguro de vida que contraté de forma independiente tiene buena cobertura: capital asegurado de {amount} euros, invalidez incluida y prima razonable. No tuve que vincularlo a ningún producto. Lo recomendaría como protección básica para una familia con hipoteca.", "Satisfacción con seguro de vida contratado sin vinculaciones obligatorias", "Productos", {"amount": ["150.000","200.000","250.000","300.000"]}),
    # --- CRÉDITO AL CONSUMO ---
    (2, "El tipo de interés del crédito al consumo que me ofrecieron era del {rate}% TAE. Para un cliente de {n} años sin incidencias es incomprensible. La competencia me ofreció la mitad. Cuando intenté negociarlo me dijeron que era la tarifa fija para todos. Sin margen de maniobra.", "Tipo de interés en crédito al consumo elevado e innegociable", "Productos", {"rate": ["16","17","18","19"], "n": ["cinco","diez","quince","ocho"]}),
    (8, "El crédito al consumo lo aprobaron en {n} minutos de forma completamente online. Sin papeleo, sin ir a la oficina. El tipo fue razonable y las condiciones claras desde el principio. Para una compra importante es una alternativa cómoda y sin sorpresas.", "Crédito al consumo aprobado digitalmente con rapidez y condiciones claras", "Productos", {"n": ["diez","quince","veinte","cinco"]}),
    # --- DEPÓSITO A PLAZO ---
    (3, "Contraté un depósito a plazo al {rate}% TAE y al vencimiento el interés aplicado fue diferente. Cuando reclamé me mostraron una cláusula en un anexo de {n} páginas que reducía el tipo en determinadas condiciones. Me siento estafado con un producto que debería ser el más sencillo del mundo.", "Condiciones reales del depósito a plazo distintas a las ofertadas inicialmente", "Productos", {"rate": ["3","3.5","2.5","4"], "n": ["cuarenta","cincuenta","treinta y cinco"]}),
    (9, "El depósito a plazo fijo al {rate}% TAE a {m} meses me ofrece certeza total sobre la rentabilidad. No hay letra pequeña, no hay vinculaciones, no hay condiciones. El importe mínimo es asequible y la renovación automática es opcional. Exactamente lo que espero de un producto de ahorro.", "Satisfacción con transparencia y condiciones claras del depósito a plazo", "Productos", {"rate": ["3","3.5","4","2.75"], "m": ["seis","doce","dieciocho","veinticuatro"]}),
    # --- CUENTA EMPRESARIAL ---
    (3, "La cuenta empresarial tiene un límite de {amount} euros diarios para transferencias que es insuficiente para mi negocio. Los pagos internacionales requieren solicitud previa con {n} días de antelación. Las comisiones son elevadas. Para una pyme es un producto completamente inadecuado.", "Cuenta empresarial con límites operativos y comisiones inadecuadas para pymes", "Productos", {"amount": ["3.000","5.000","10.000"], "n": ["dos","tres","cuatro"]}),
    (8, "La cuenta empresarial me permite gestionar cobros, pagos a proveedores y nóminas todo desde la misma plataforma. Las transferencias nacionales son inmediatas. El {n}% de descuento en el TPV es un ahorro real. Para mi pequeño negocio es la solución ideal.", "Satisfacción con funcionalidades de cuenta empresarial para pequeño negocio", "Productos", {"n": ["10","15","20","25"]}),
    # --- ETFs / INVERSIÓN ---
    (8, "La gama de ETFs disponibles es amplia: mercados desarrollados, emergentes, sectoriales y temáticos. Las comisiones de compraventa son de {rate}% sin mínimo por operación. Puedo operar directamente desde la app. Para un inversor pasivo es la mejor plataforma que he encontrado en banca tradicional.", "Buena oferta de ETFs con comisiones competitivas y acceso desde app", "Productos", {"rate": ["0.1","0.15","0.2","0.12"]}),
    (5, "Tienen una selección razonable de ETFs de mercados desarrollados pero escasa en emergentes y alternativos. Las comisiones son aceptables aunque no las más bajas del mercado. La plataforma de negociación es funcional pero poco visual. Cumple para el inversor básico pero no para perfiles avanzados.", "Oferta de ETFs correcta pero limitada para inversores con perfil avanzado", "Productos", {}),
    # --- RENTING ---
    (7, "Contraté un renting de coche a través del banco y el proceso fue muy sencillo. La cuota mensual incluye seguro, mantenimiento y cambio de neumáticos. Sin sorpresas ni costes adicionales. Para alguien que no quiere preocuparse por el coche es una solución cómoda y predecible.", "Satisfacción con producto de renting de vehículo integrado con banco", "Productos", {}),
    (3, "El renting que me ofrecieron tenía una letra pequeña con penalizaciones por exceso de kilómetros que triplicaban la cuota mensual. Nadie me lo explicó claramente. Al entregar el coche me pasaron una factura inesperada de {amount} euros. Un producto poco transparente y con sorpresas al final.", "Penalizaciones ocultas en contrato de renting no explicadas al contratar", "Productos", {"amount": ["800","1.200","600","1.500"]}),
    # --- LÍNEA DE CRÉDITO ---
    (9, "La línea de crédito para mi empresa es muy flexible: solo pago intereses sobre el importe que uso, no sobre el total disponible. Puedo disponer y devolver cuando quiero. El tipo es competitivo para el mercado actual. Es el producto de financiación más útil que tengo contratado.", "Satisfacción con flexibilidad y coste de línea de crédito empresarial", "Productos", {}),
    (2, "Me aprobaron una línea de crédito de {amount} euros pero con tantas condiciones que es casi imposible usarla: avales necesarios, revisión trimestral y posibilidad de cancelación unilateral por el banco. Más que un producto de financiación parece una trampa llena de restricciones.", "Línea de crédito con condiciones restrictivas que dificultan su uso", "Productos", {"amount": ["20.000","30.000","50.000","15.000"]}),
]

# =============================================================================
# CANALES
# =============================================================================
TEMPLATES += [
    # --- APP MÓVIL positivo ---
    (10, "La app móvil es increíblemente rápida e intuitiva. En menos de {n} segundos puedo hacer cualquier gestión: transferencias, inversiones, consultar movimientos o hablar con mi gestor. El diseño es moderno y nunca se cuelga. Es la mejor aplicación bancaria que he usado.", "Excelente experiencia de uso de la app móvil en velocidad y diseño", "Canales", {"n": ["treinta","cuarenta","veinte"]}),
    (9, "La app tiene reconocimiento facial y huella dactilar para acceder. El proceso es instantáneo y muy seguro. Además puedo personalizar el orden de los accesos directos según mis hábitos. La experiencia de usuario es la mejor que he tenido en cualquier app bancaria.", "Excelente seguridad biométrica y personalización en la app", "Canales", {}),
    (9, "La función de presupuestador de la app clasifica automáticamente mis gastos en categorías y me muestra gráficos semanales y mensuales. Me ha ayudado a detectar gastos recurrentes que no recordaba tener. Es una herramienta de finanzas personales muy completa integrada en el banco.", "Presupuestador automático en app útil para control de gastos personales", "Canales", {}),
    (8, "Desde la app puedo contratar productos, hacer reclamaciones, firmar documentos y contactar con mi gestor por videollamada. Llevo {n} meses sin necesitar ir a la sucursal para nada. La digitalización del banco es genuina y no solo cosmética.", "App completa que permite gestión íntegra sin visitar sucursal", "Canales", {"n": ["ocho","doce","dieciocho","seis"]}),
    (8, "Las notificaciones push de cada pago con tarjeta son instantáneas y muy claras. Me ayudan a detectar cualquier cargo inesperado de forma inmediata. Gracias a esto detecté un cargo fraudulento en menos de {n} minutos y pude bloquearlo desde la misma notificación.", "Notificaciones instantáneas de pagos útiles para detección de fraude", "Canales", {"n": ["dos","tres","cinco"]}),
    # --- APP MÓVIL negativo ---
    (2, "La app se cierra sola {n} o {m} veces al día. He reportado el problema en {times} ocasiones y solo me dicen que están trabajando en ello. Cada actualización empeora el rendimiento. Llevo {months} meses con la misma situación sin ninguna solución.", "Fallos recurrentes de estabilidad en la app sin resolución tras múltiples reportes", "Canales", {"n": ["tres","cuatro","cinco"], "m": ["cuatro","cinco","seis"], "times": ["tres","cuatro","cinco"], "months": ["tres","cuatro","seis"]}),
    (3, "La app no está optimizada para tablets. Los menús se ven cortados y muchos botones no responden. Tampoco funciona bien en el último sistema operativo iOS. Para una empresa bancaria que dice apostar por lo digital es una vergüenza tener una app tan mal adaptada.", "App bancaria mal optimizada para tablets y versiones recientes de sistema operativo", "Canales", {}),
    (4, "Después de la última actualización la app tardó {n} días en funcionar con normalidad. Hubo transacciones que no se procesaron correctamente y tuve que ir a la oficina a resolverlas. Las actualizaciones deberían probarse antes de lanzarlas masivamente a los clientes.", "Actualización de app que causó fallos en transacciones y requirió visita a sucursal", "Canales", {"n": ["dos","tres","cuatro"]}),
    (1, "La app me bloqueó la cuenta sin motivo aparente justo antes de un viaje importante. No pude operar durante {n} días. El proceso de desbloqueo requirió ir a la oficina con documentación original. Nadie me explicó por qué se bloqueó. Un sistema de seguridad que penaliza al cliente legítimo.", "Bloqueo injustificado de cuenta por la app en momento crítico sin explicación", "Canales", {"n": ["dos","tres","cuatro","cinco"]}),
    # --- BANCA ONLINE / WEB ---
    (9, "La banca online permite gestionar absolutamente todo: contratar productos, ver histórico de {n} años, descargar certificados y configurar alertas. Los tiempos de carga son rápidos incluso en conexión lenta. Es la plataforma web bancaria más completa que he usado.", "Banca online completa y rápida con acceso a histórico extenso", "Canales", {"n": ["cinco","diez","tres","siete"]}),
    (2, "La página web del banco es lentísima. Para ver los movimientos del último mes tarda más de {n} segundos en cargar. Además falla constantemente en Chrome y Firefox. Cuando llamo para reportarlo me dicen que pruebe con otro navegador. Una solución inaceptable en pleno siglo XXI.", "Web bancaria lenta y con errores en navegadores principales", "Canales", {"n": ["treinta","cuarenta","veinte","cincuenta"]}),
    (4, "La web no está adaptada para móvil. Los botones son minúsculos y se superponen unos sobre otros. Los PDFs de los extractos no se abren desde el navegador del móvil. Si no tengo ordenador cerca es prácticamente imposible hacer ciertas gestiones.", "Web bancaria no adaptada para uso en dispositivos móviles", "Canales", {}),
    (6, "La web es funcional y permite hacer las gestiones básicas. El diseño es algo anticuado pero los menús son fáciles de entender. A veces va lenta en horas pico. No es la mejor experiencia digital pero tampoco impide operar con normalidad.", "Web bancaria funcional pero con diseño anticuado y rendimiento variable", "Canales", {}),
    # --- CAJERO AUTOMÁTICO ---
    (1, "El cajero de mi sucursal habitual lleva más de {n} semanas fuera de servicio. El siguiente más cercano está a {km} kilómetros. He llamado varias veces para reportarlo y nadie lo repara. Para los clientes mayores que dependen del efectivo es una situación completamente inadmisible.", "Cajero averiado sin reparar durante semanas con impacto en clientes dependientes de efectivo", "Canales", {"n": ["tres","cuatro","cinco","dos"], "km": ["tres","cuatro","cinco","dos"]}),
    (8, "Los cajeros del banco están distribuidos por toda la ciudad y rara vez están fuera de servicio. El proceso de operación es rápido e intuitivo. Además puedo hacer ingresos en efectivo en la mayoría de ellos. Un servicio de cajeros fiable y bien mantenido.", "Buena disponibilidad y mantenimiento de la red de cajeros", "Canales", {}),
    (9, "Desde la app puedo retirar efectivo en cualquier cajero del banco sin tarjeta física usando solo el móvil. Genero un código QR y lo escaneo en el cajero. Es muy útil cuando olvido la cartera. Una funcionalidad práctica que no he visto en otros bancos.", "Extracción de efectivo sin tarjeta mediante código QR desde app", "Canales", {}),
    (5, "Los cajeros funcionan correctamente para las operaciones básicas. Sin embargo algunos modelos más antiguos tienen la pantalla muy deteriorada y es difícil leer. Para ingresar efectivo solo funcionan {n} de los {m} cajeros de mi oficina habitual. Podría mejorarse la inversión en mantenimiento.", "Funcionamiento básico de cajeros con deterioro en equipos más antiguos", "Canales", {"n": ["uno","dos"], "m": ["tres","cuatro","cinco"]}),
    # --- SUCURSAL / OFICINA ---
    (1, "La cola en la oficina era de más de {n} hora el martes por la mañana con solo {m} empleados para atender a más de {p} personas. El sistema de cita previa falla y no deja reservar. Es un servicio completamente colapsado que no funciona.", "Colapso total en atención presencial de la sucursal sin cita previa funcional", "Canales", {"n": ["una","hora y media"], "m": ["dos","tres"], "p": ["veinte","treinta","veinticinco"]}),
    (7, "La oficina está bien ubicada en el centro con aparcamiento cercano. Los jueves tienen horario de tarde hasta las {n}, lo cual es muy útil si trabajas. La sala de espera es cómoda. Podría mejorar el tiempo medio de espera pero en general es accesible.", "Buena accesibilidad y ubicación de sucursal con horario de tarde", "Canales", {"n": ["19:00","18:30","18:00"]}),
    (2, "La oficina solo abre de lunes a viernes de {h1} a {h2}. Para alguien que trabaja en esas horas es imposible ir. No tienen horario de tarde ni sábados. La única alternativa es pedir cita con semanas de antelación. El banco no se ha adaptado a los horarios reales de la vida laboral.", "Horario de sucursal incompatible con jornada laboral sin alternativa de tarde o sábado", "Canales", {"h1": ["8:30","9:00"], "h2": ["14:00","13:30"]}),
    (8, "Pedir cita previa online es muy sencillo: en menos de {n} minutos tienes confirmación y un recordatorio por SMS el día anterior. El día de la cita no tuve que esperar nada. La digitalización del proceso presencial está muy bien implementada.", "Sistema de cita previa online ágil y efectivo sin esperas", "Canales", {"n": ["dos","tres","cinco"]}),
    # --- TELÉFONO / CALL CENTER ---
    (3, "El teléfono de atención al cliente tiene una espera media de {n} minutos. El menú de voz tiene {m} niveles de opciones antes de poder hablar con alguien. Muchas veces me han cortado la llamada en la espera. Es el canal más frustrante de todos los que ofrece el banco.", "Esperas excesivas y menú telefónico complejo que dificulta contacto con agente", "Canales", {"n": ["cuarenta","treinta","cincuenta","cuarenta y cinco"], "m": ["cuatro","cinco","tres"]}),
    (8, "Cuando llamé con una incidencia urgente me atendieron en menos de {n} minutos. El agente fue directo y resolutivo. Solucionó el problema en la misma llamada sin derivarme a otro departamento. Una atención telefónica que raramente encuentro en otros bancos.", "Atención telefónica rápida y resolutiva sin transferencias innecesarias", "Canales", {"n": ["cinco","cuatro","tres","seis"]}),
    (4, "El horario del servicio telefónico es de {h1} a {h2}. Si tienes una urgencia fuera de ese horario no puedes contactar con nadie. Para bloquear una tarjeta o reportar un fraude en fin de semana hay un número de emergencias pero no sirve para nada más. Muy limitado.", "Horario de atención telefónica limitado sin cobertura para urgencias generales", "Canales", {"h1": ["8:00","9:00"], "h2": ["20:00","21:00"]}),
    # --- BIZUM ---
    (10, "Bizum funciona perfectamente desde la app. En menos de {n} segundos puedo enviar o solicitar dinero a cualquier contacto. Las solicitudes de pago también funcionan muy bien. Lo uso a diario para dividir gastos y nunca ha fallado. Simplísimo y fiable.", "Satisfacción total con Bizum integrado en app por velocidad y fiabilidad", "Canales", {"n": ["diez","quince","veinte"]}),
    (7, "El Bizum funciona bien para pagos básicos entre contactos. El límite de {amount} euros por operación cubre la mayoría de mis necesidades. Solo echo de menos poder programar Bizums recurrentes para pagos fijos mensuales. En general una funcionalidad bien integrada.", "Satisfacción con Bizum con sugerencia de mejora para pagos recurrentes", "Canales", {"amount": ["500","1.000","2.000"]}),
    (3, "El Bizum del banco tiene un límite de {amount} euros diarios muy restrictivo comparado con otros bancos. Además hay un máximo de {n} operaciones al día. Para alguien que usa Bizum para negocios pequeños estas limitaciones son un serio problema operativo.", "Limitaciones excesivas de Bizum por importe y número de operaciones diarias", "Canales", {"amount": ["200","300","500"], "n": ["diez","cinco","ocho"]}),
    # --- CHATBOT / ASISTENTE VIRTUAL ---
    (8, "El chatbot resuelve perfectamente las consultas habituales: saldo, últimos movimientos, bloqueo de tarjeta o estado de una transferencia. Cuando no puede resolver algo deriva a un agente humano de forma fluida. Está disponible las {n} horas y eso tiene mucho valor.", "Chatbot funcional para gestiones habituales con derivación fluida a agente", "Canales", {"n": ["24","veinticuatro"]}),
    (4, "El chatbot no entiende preguntas complejas. Responde siempre con respuestas genéricas que no se adaptan a mi situación. Cuando insisto me manda a un FAQ que tampoco resuelve mi duda. Al final tengo que llamar o ir a la oficina de todas formas. Un asistente inútil.", "Chatbot incapaz de resolver consultas específicas y no genéricas", "Canales", {}),
    # --- VIDEOLLAMADA ---
    (9, "La posibilidad de hacer videollamadas con mi gestor desde casa es muy cómoda. La calidad de imagen y sonido es buena. Puedo firmar documentos digitalmente durante la llamada. Me ahorra desplazamientos para gestiones importantes. Es una funcionalidad que debería ser estándar en todos los bancos.", "Satisfacción con videollamada con gestor para firma digital de documentos", "Canales", {}),
    (5, "Las videollamadas con el banco están disponibles pero hay que reservarlas con {n} días de antelación mínimo. La imagen es buena pero el audio falla a veces. Para gestiones urgentes no es una opción viable. Como complemento al canal presencial cumple pero podría ser más ágil.", "Videoconferencia disponible pero con limitaciones de disponibilidad y audio", "Canales", {"n": ["dos","tres","cuatro"]}),
    # --- PAGO POR MÓVIL / NFC ---
    (10, "El pago por móvil funciona en todos los comercios con terminal contactless. La autenticación es instantánea con huella dactilar. Ya no necesito llevar la cartera para compras del día a día. La experiencia de pago es más rápida que con tarjeta física. Un avance real en comodidad.", "Pago por móvil completamente funcional que elimina necesidad de cartera física", "Canales", {}),
    (6, "El pago con el móvil funciona en la mayoría de comercios pero he tenido algunos problemas en gasolineras y parking automáticos. El proceso de configuración inicial fue algo complejo. Una vez configurado es cómodo para el día a día aunque con margen de mejora en compatibilidad.", "Pago por móvil funcional con problemas de compatibilidad en algunos terminales", "Canales", {}),
    # --- CITA PREVIA ---
    (4, "El sistema de cita previa online falla constantemente. A veces te confirma la cita pero no aparece en el sistema cuando llegas. He llegado con cita reservada {n} veces y me han dicho que no constaba. Un sistema de gestión de citas completamente poco fiable.", "Sistema de cita previa con fallos que invalidan reservas confirmadas", "Canales", {"n": ["dos","tres"]}),
    (8, "La cita previa online se puede reservar a cualquier hora del día. En {n} minutos tienes confirmación por email y SMS con todos los detalles. El día de la cita el tiempo de espera fue de menos de {m} minutos. Un sistema que respeta el tiempo del cliente.", "Sistema de cita previa digital eficiente con tiempos de espera mínimos", "Canales", {"n": ["dos","tres","cinco"], "m": ["cinco","tres","dos"]}),
    # --- ALERTAS Y SEGURIDAD ---
    (9, "Las alertas de seguridad me notifican de inmediato ante cualquier intento de acceso inusual. Puedo bloquear la tarjeta desde la app en segundos. El doble factor de autenticación funciona perfectamente. Gracias a este sistema detecté un intento de fraude y evité perder {amount} euros.", "Sistema de alertas y seguridad digital que permitió evitar fraude", "Canales", {"amount": ["200","500","1.000","300"]}),
    (3, "Las alertas de seguridad están desactivadas por defecto y no es fácil encontrar cómo activarlas. Cuando tuve un cargo fraudulento me enteré días después al revisar el extracto. Un banco que apuesta por la seguridad debería tener estas alertas activadas por defecto.", "Alertas de seguridad desactivadas por defecto con difícil configuración", "Canales", {}),
    # --- TRANSFERENCIAS ONLINE ---
    (9, "Las transferencias inmediatas funcionan perfectamente {n} horas al día los {m} días de la semana. El dinero llega en menos de {s} segundos. Sin límite de horario ni recargo adicional. Para operaciones urgentes es una funcionalidad imprescindible que este banco tiene perfectamente implementada.", "Transferencias inmediatas disponibles 24/7 sin costes adicionales", "Canales", {"n": ["24","veinticuatro"], "m": ["365","trescientos sesenta y cinco"], "s": ["diez","veinte","treinta"]}),
    (2, "Al intentar hacer una transferencia urgente de {amount} euros la plataforma online me la bloqueó sin explicación. Tardé {n} días en desbloquearla. Tuve que ir a la oficina con documentación. La incidencia me generó problemas graves con el receptor del pago. Inaceptable.", "Bloqueo injustificado de transferencia urgente con proceso de desbloqueo presencial", "Canales", {"amount": ["2.000","5.000","3.000","1.500"], "n": ["dos","tres","cuatro"]}),
    # --- DOCUMENTACIÓN DIGITAL ---
    (8, "Todos mis contratos, extractos y certificados están disponibles de forma digital en la app. Puedo descargar cualquier documento de los últimos {n} años en PDF. Nunca necesito llamar para pedir documentación. Esto ahorra mucho tiempo y papel. La digitalización documental es sobresaliente.", "Archivo documental digital completo y accesible desde la app", "Canales", {"n": ["cinco","diez","tres","siete"]}),
    (3, "Los extractos de cuenta solo están disponibles online para los últimos {n} meses. Para documentación más antigua hay que solicitarla en oficina con {m} días de antelación y a veces cobran por ello. En plena era digital limitar el acceso al histórico es completamente injustificable.", "Historial documental digital limitado con cobro por documentación antigua", "Canales", {"n": ["tres","seis","doce"], "m": ["cinco","diez","siete"]}),
]

# =============================================================================
# PERSONAL
# =============================================================================
TEMPLATES += [
    # --- GESTOR PERSONAL positivo ---
    (10, "Mi gestor personal se adelanta siempre a mis necesidades. Antes de que yo lo piense me llama para ofrecerme soluciones. Llevo {n} años con él y ha gestionado perfectamente momentos complejos como la compra de mi casa o la planificación de mi jubilación. Un profesional excepcional.", "Gestor proactivo que anticipa necesidades del cliente con relación de largo plazo", "Personal", {"n": ["cinco","ocho","diez","doce"]}),
    (9, "Mi gestora conoce perfectamente mi situación financiera, mis objetivos y mis aversiones al riesgo. Nunca me ha propuesto un producto que no se ajuste a mi perfil. Sus recomendaciones han sido siempre acertadas. Es exactamente el tipo de asesoramiento que espero de un banco de confianza.", "Asesora con conocimiento profundo del perfil y objetivos del cliente", "Personal", {}),
    (10, "Tuve una situación económica muy difícil y mi asesora me ayudó a reestructurar mis deudas sin juzgarme. Me propuso un plan realista y me fue acompañando durante todo el proceso. Gracias a su gestión pude superar una situación que parecía imposible. Le estaré siempre agradecido.", "Asesora empática que gestionó reestructuración de deuda con éxito en momento difícil", "Personal", {}),
    (9, "Mi gestor me responde por mensaje en menos de {n} hora en horario laboral. No necesito llamar ni ir a la oficina para resolver dudas rápidas. Esta disponibilidad ágil transforma la relación con el banco. Se siente como tener un asesor de confianza siempre disponible.", "Gestor muy accesible por mensajería con respuesta rápida", "Personal", {"n": ["una","media"]}),
    (8, "Mi gestor siempre me explica cada producto con claridad antes de contratarlo: ventajas, riesgos y alternativas. Nunca me ha presionado ni me ha hecho sentir ignorante. Gracias a su forma de trabajar confío plenamente en sus recomendaciones. Es el mayor activo que tiene el banco para mí.", "Gestor que explica con claridad y sin presión antes de recomendar productos", "Personal", {}),
    # --- GESTOR PERSONAL negativo ---
    (1, "El asesor comercial me presionó para contratar un producto de inversión que no necesitaba sin explicarme los riesgos. Fue evasivo con mis preguntas. Meses después el producto acumulaba pérdidas significativas. Cuando reclamé me dijo que yo había firmado el contrato. Una mala praxis comercial inaceptable.", "Venta agresiva de producto inadecuado sin transparencia sobre riesgos reales", "Personal", {}),
    (3, "Es imposible contactar con mi gestor asignado. No coge el teléfono, no responde emails y cuando llamo a la oficina siempre está ocupado. Para cualquier gestión tengo que ir en persona porque el canal directo con mi gestor está completamente roto.", "Inaccesibilidad total del gestor asignado por todos los canales disponibles", "Personal", {}),
    (4, "En los últimos {n} años he tenido {m} gestores diferentes asignados. Cada cambio implica explicar toda mi situación desde cero porque nadie traspasa correctamente el histórico. Esta rotación constante hace imposible construir una relación bancaria de confianza.", "Alta rotación de gestores que impide continuidad y relación de confianza", "Personal", {"n": ["dos","tres","cuatro"], "m": ["cuatro","cinco","seis","tres"]}),
    (2, "El asesor me recomendó un fondo de inversión con un perfil de riesgo muy superior al mío sin advertirme. Cuando perdí dinero significativo me presentó el contrato que yo había firmado como única respuesta. Un asesoramiento irresponsable que incumple claramente la normativa MiFID.", "Asesoramiento que incumple normativa MiFID al no ajustarse al perfil de riesgo del cliente", "Personal", {}),
    # --- EMPLEADO DE VENTANILLA ---
    (8, "La empleada de ventanilla que me atendió fue muy amable y eficiente. Resolvió mi consulta en {n} minutos, me explicó todas las opciones disponibles y me ayudó a elegir la mejor. Una atención presencial que supera las expectativas.", "Atención eficiente y amable en ventanilla con buena orientación al cliente", "Personal", {"n": ["cinco","diez","ocho"]}),
    (3, "El empleado de ventanilla que me atendió tenía poca formación sobre los productos digitales del banco. Me dio información incorrecta sobre una funcionalidad de la app. Si los empleados presenciales no conocen sus propios productos, ¿cómo pueden asesorar a los clientes?", "Empleado de ventanilla con conocimiento insuficiente sobre productos digitales del banco", "Personal", {}),
    (5, "Los empleados de ventanilla son amables y el ambiente es tranquilo. Sin embargo las colas son largas y los procesos lentos. Para operaciones sencillas como ingresar un cheque tardé más de {n} minutos. El trato es bueno pero la eficiencia operativa es mejorable.", "Buen trato en ventanilla pero procesos lentos con colas largas", "Personal", {"n": ["veinte","treinta","veinticinco"]}),
    # --- AGENTE TELEFÓNICO ---
    (9, "Cuando llamé con una incidencia urgente el agente me atendió en {n} minutos y resolvió el problema sin derivarme a ningún otro departamento. Fue empático, claro y eficiente. Este tipo de atención telefónica es lo que marca la diferencia respecto a la competencia.", "Agente telefónico empático y resolutivo sin derivaciones en incidencia urgente", "Personal", {"n": ["tres","cuatro","cinco","dos"]}),
    (2, "El agente telefónico que me atendió cuando denuncié un cargo fraudulento no supo cómo gestionar la incidencia. Me transfirió {n} veces a distintos departamentos. Ninguno tomó medidas. Tardé {m} días en recuperar el dinero. La gestión telefónica del fraude es deficiente.", "Gestión deficiente de fraude por agentes sin capacitación ni coordinación", "Personal", {"n": ["tres","cuatro","cinco"], "m": ["cinco","siete","diez"]}),
    (3, "Los agentes del call center no tienen capacidad para tomar ninguna decisión autónoma. Todo lo derivan a la oficina o a otro departamento. Son incapaces de resolver nada por sí mismos. El canal telefónico existe pero no sirve para gestiones que requieran alguna resolución.", "Agentes telefónicos sin autonomía para resolver incidencias de forma independiente", "Personal", {}),
    (7, "El servicio telefónico resuelve bien las consultas básicas de forma rápida. Para gestiones más complejas hay que esperar más tiempo pero eventualmente se resuelven. La calidad del servicio depende mucho de qué agente te toca. Bastante desigual pero en promedio funciona.", "Calidad de atención telefónica variable según agente con resultado promedio aceptable", "Personal", {}),
    # --- DIRECTOR DE OFICINA ---
    (2, "El director de la oficina fue muy brusco cuando presenté una reclamación formal. Me interrumpió varias veces y minimizó mi problema. Al final me remitió a enviar un email sin resolver nada. Me fui de la oficina sintiéndome humillado y sin solución.", "Trato irrespetuoso del director de oficina ante reclamación formal del cliente", "Personal", {}),
    (9, "El director de la oficina intervino personalmente para resolver una incidencia compleja que otros empleados no habían podido solucionar. Fue directo, eficiente y empático. En menos de {n} minutos el problema estaba resuelto. Un directivo que lidera con el ejemplo.", "Director de oficina que interviene eficazmente para resolver incidencias complejas", "Personal", {"n": ["quince","veinte","treinta"]}),
    # --- ASESOR DE BANCA PRIVADA ---
    (10, "El servicio de banca privada es excepcional. Mi asesor dedica tiempo real a conocer mis objetivos y personales. Las reuniones de seguimiento son frecuentes y productivas. Me siento completamente acompañado en cada decisión financiera importante. Justifica ampliamente lo que cuesta.", "Excelente servicio de banca privada con asesoramiento personalizado profundo", "Personal", {}),
    (7, "El asesor de banca privada tiene buenos conocimientos de mercados y fiscalidad. Las reuniones son productivas aunque a veces me parece que intenta vender productos de la propia gestora del banco antes que opciones de terceros. En general el asesoramiento es de calidad.", "Buen asesoramiento en banca privada con posible sesgo hacia productos propios", "Personal", {}),
    # --- TRATO / EXPERIENCIA GENERAL ---
    (10, "Todo el equipo de mi oficina es extraordinariamente profesional. Siempre con una sonrisa, resuelven cualquier incidencia al momento y me hacen sentir un cliente importante. Es el nivel de servicio que no he encontrado en ningún otro banco en {n} años.", "Excelencia generalizada en profesionalidad y calidez del equipo de la sucursal", "Personal", {"n": ["diez","quince","veinte","doce"]}),
    (2, "El trato que recibí en la oficina fue condescendiente y poco profesional. El empleado me habló como si no entendiese nada de finanzas y respondió con impaciencia cuando pregunté. Me fui sintiéndome un cliente de segunda. Inaceptable en un banco que dice valorar a sus clientes.", "Trato condescendiente e irrespetuoso por parte de empleado de sucursal", "Personal", {}),
    (4, "Cada vez que voy a la oficina o llamo me atiende una persona diferente y nadie conoce mi historial. Tengo que repetir siempre la misma información desde cero. Esta descoordinación interna hace la relación con el banco completamente impersonal y frustrante.", "Descoordinación interna que obliga al cliente a repetir información en cada contacto", "Personal", {}),
    # --- RECLAMACIONES ---
    (10, "Cuando presenté una reclamación formal me llamaron en menos de {n} horas para darme respuesta. La persona fue empática y resolvió el problema de forma justa devolviendo el importe en el acto. Una gestión de reclamaciones que genera confianza y fidelidad.", "Resolución rápida y justa de reclamación con devolución inmediata", "Personal", {"n": ["24","48","36"]}),
    (2, "Mi reclamación formal lleva {n} meses sin resolución. Me han llamado {m} veces para pedirme más información que ya había enviado. Cada llamada es de una persona diferente que no conoce el caso. El proceso de reclamaciones parece diseñado para que el cliente se rinda.", "Proceso de reclamación prolongado con falta de coordinación interna y seguimiento", "Personal", {"n": ["tres","cuatro","dos"], "m": ["dos","tres","cuatro"]}),
    # --- FORMACIÓN E INFORMACIÓN ---
    (8, "Cuando tengo dudas sobre productos o normativa fiscal los empleados del banco siempre me dan información correcta y actualizada. Me parece que el banco invierte en formación continua de su plantilla. Eso se nota y se agradece cuando uno necesita asesoramiento de verdad.", "Personal bien formado que da información correcta y actualizada sobre productos y fiscalidad", "Personal", {}),
    (3, "Los empleados de la oficina no están actualizados sobre los productos digitales del banco. Cuando pregunté por una funcionalidad de la app me dieron información que llevaba meses obsoleta. Si ellos no saben cómo funcionan sus propios productos, ¿cómo van a asesorar a los clientes?", "Personal no actualizado sobre productos y funcionalidades digitales del propio banco", "Personal", {}),
    # --- ATENCIÓN A COLECTIVOS ---
    (8, "Al hablar en catalán el empleado me respondió en el mismo idioma sin ningún problema. Toda la documentación también está disponible en catalán. Es un detalle que valoro mucho y que demuestra respeto por la diversidad lingüística de los clientes.", "Atención en lengua propia y documentación en catalán disponible en la sucursal", "Personal", {}),
    (3, "Cuando mi madre mayor fue a la oficina a hacer una gestión sencilla el empleado le habló muy rápido con jerga financiera que ella no entendía. Nadie tuvo la paciencia de explicarle las cosas despacio. El banco necesita formación en atención a clientes mayores.", "Falta de adaptación en la atención a clientes mayores con menor alfabetización financiera", "Personal", {}),
    (9, "El banco tiene un servicio de acompañamiento para clientes mayores muy bien implementado. Cuando acompañé a mi padre, el gestor le explicó todo con paciencia, en términos sencillos y sin prisa. Es un ejemplo de cómo debería ser la atención a un colectivo vulnerable.", "Excelente atención personalizada a clientes mayores con paciencia y lenguaje sencillo", "Personal", {}),
    # --- COMERCIALIZACIÓN ---
    (5, "El equipo comercial llama con demasiada frecuencia para ofrecer productos. En el último mes he recibido {n} llamadas no solicitadas. Entiendo que hay objetivos comerciales pero la insistencia genera rechazo. Una política de contacto más moderada sería más efectiva.", "Exceso de llamadas comerciales no solicitadas que genera rechazo en el cliente", "Personal", {"n": ["cuatro","cinco","seis","tres"]}),
    (8, "Cuando el banco me llama para ofrecerme algo siempre es algo que realmente me puede interesar según mi perfil. Nunca me han ofrecido algo completamente fuera de lugar. Se nota que hay un trabajo de segmentación detrás. Es una comercialización inteligente que no molesta.", "Comercialización segmentada y relevante que el cliente valora positivamente", "Personal", {}),
]

# =============================================================================
# PRICING
# =============================================================================
TEMPLATES += [
    # --- SIN COMISIONES / BUENAS CONDICIONES ---
    (10, "Este banco no cobra comisión de ningún tipo: ni por mantenimiento de cuenta, ni por transferencias nacionales, ni por usar cajeros propios o de otras entidades. Todo incluido sin condiciones ocultas. No esperaba encontrar un banco sin comisiones con tan buen servicio integral.", "Cero comisiones en todos los servicios sin condiciones ocultas", "Pricing", {}),
    (9, "La cuenta nómina no tiene comisión de mantenimiento con solo domiciliar la nómina. Una condición muy sencilla que me da acceso a tarjeta de débito gratuita y transferencias sin coste. La mejor relación precio-valor que he encontrado en la banca tradicional.", "Cuenta nómina sin comisión con condición de domiciliación sencilla y alcanzable", "Pricing", {}),
    (9, "Por domiciliar {n} recibos en la cuenta me eliminaron todas las comisiones y me redujeron el diferencial de la hipoteca en {rate} puntos básicos. El ahorro anual real es de más de {savings} euros. Las condiciones de vinculación son alcanzables y los beneficios son tangibles.", "Ahorro significativo por vinculación con condiciones de domiciliación alcanzables", "Pricing", {"n": ["tres","cuatro","cinco"], "rate": ["diez","quince","veinte","veinticinco"], "savings": ["500","800","1.000","1.200"]}),
    (10, "Cuando comparé hipotecas en el mercado este banco tenía el tipo fijo más bajo: un {rate}% frente a la media del {rate2}% del sector. A {n} años de hipoteca la diferencia es de decenas de miles de euros. Una ventaja competitiva en precio que marca la elección.", "Tipo fijo hipotecario más competitivo del mercado con ahorro objetivamente calculable", "Pricing", {"rate": ["2.75","2.8","2.9","3.0"], "rate2": ["3.3","3.4","3.5","3.2"], "n": ["veinte","veinticinco","treinta"]}),
    (8, "El cashback del {rate}% en supermercados, gasolineras y restaurantes se aplica automáticamente sin activación manual. El mes pasado recuperé {amount} euros solo con gastos habituales. Es un beneficio real y tangible que otros bancos no ofrecen con tanta sencillez.", "Cashback automático aplicado correctamente en categorías de gasto cotidiano", "Pricing", {"rate": ["2","3","5"], "amount": ["30","50","80","40"]}),
    (9, "La tarjeta de crédito no tiene cuota anual y tampoco cobra por operaciones en moneda extranjera. En mis {n} viajes de este año no he pagado un solo euro en comisiones por cambio de divisa. Para alguien que viaja habitualmente es una tarjeta con un precio imbatible.", "Tarjeta sin comisión anual ni por divisa ideal para clientes viajeros frecuentes", "Pricing", {"n": ["tres","cuatro","cinco","seis"]}),
    (8, "El tipo de interés de la hipoteca variable es Euríbor más {rate}%. Un diferencial muy competitivo. Además puedo hacer novación a tipo fijo sin coste en cualquier momento. Esta flexibilidad en el precio de la hipoteca me parece un valor diferencial importante.", "Diferencial hipotecario competitivo con opción de novación a fijo sin coste", "Pricing", {"rate": ["0.5","0.6","0.75","0.4"]}),
    (7, "El precio del seguro de hogar es razonable para la cobertura que ofrece. He comparado con {n} aseguradoras y el banco está en la media del mercado pero con la ventaja de tenerlo todo centralizado. Sin vinculaciones obligatorias. Una opción equilibrada en precio.", "Precio de seguro de hogar competitivo con ventaja de centralización sin vinculaciones", "Pricing", {"n": ["tres","cuatro","cinco"]}),
    (8, "Por tener la nómina y los recibos domiciliados recibo una bonificación de {amount} euros al año. La condición es fácil de cumplir y la bonificación llega puntualmente cada {period}. Una forma honesta y simple de premiar la vinculación del cliente.", "Bonificación por vinculación sencilla que el banco aplica con puntualidad", "Pricing", {"amount": ["100","150","200","120"], "period": ["trimestre","semestre","año"]}),
    (9, "La cuenta de ahorro da un {rate}% TAE sin vinculaciones obligatorias ni plazos mínimos. El dinero está disponible en cualquier momento. Con la inflación controlándose es una buena opción para el ahorro a corto plazo. El mejor tipo que he encontrado en banca tradicional.", "Cuenta ahorro con tipo competitivo y disponibilidad inmediata sin condiciones", "Pricing", {"rate": ["3","3.5","2.5","4","2.75"]}),
    # --- COMISIONES ALTAS / MAL PRICING ---
    (1, "Me notificaron por carta que subían las comisiones de mantenimiento un {rate}% con solo {n} días de preaviso. Sin posibilidad de negociación. Un cambio unilateral de condiciones que vulnera la confianza del cliente y me obliga a buscar alternativas urgentemente.", "Subida unilateral de comisiones con preaviso mínimo sin posibilidad de negociación", "Pricing", {"rate": ["30","40","50","60"], "n": ["quince","diez","veinte"]}),
    (2, "Las comisiones de este banco son las más altas del mercado. Cobran {amount} euros al mes solo por mantener la cuenta abierta. Por cada transferencia cobran {fee} euros. Por sacar en cajero de otro banco otros {cajero} euros. Es un banco diseñado para ganar dinero con las comisiones.", "Estructura de comisiones entre las más elevadas del mercado sin beneficios compensadores", "Pricing", {"amount": ["15","18","20","12"], "fee": ["0.5","1","2"], "cajero": ["2","3","2.5"]}),
    (3, "Cobran comisión por hacer una transferencia SEPA dentro de la Unión Europea. Esto lleva años siendo contrario a la normativa europea. Ellos la envuelven como gasto de gestión pero es lo mismo. Una práctica que perjudica al cliente y que debería estar prohibida.", "Cobro encubierto por transferencia SEPA contrario a regulación europea", "Pricing", {}),
    (2, "Las comisiones de custodia de mi cartera de valores superan el {rate}% anual del patrimonio gestionado. Además cobran por cada operación de compraventa. Sumando todo, el banco se lleva más que los propios rendimientos del portfolio. Un coste completamente injustificado.", "Comisiones de custodia de valores que superan los rendimientos del portfolio", "Pricing", {"rate": ["1","1.5","2","0.8"]}),
    (2, "Me acaban de cobrar {amount} euros por recibir una transferencia desde el extranjero. Esta comisión no aparece en el resumen de tarifas principal sino en un anexo de {n} páginas. Esta opacidad en los precios parece diseñada para que el cliente no se entere hasta que ya es tarde.", "Comisión por transferencia recibida oculta en documentación extensa y difícil de encontrar", "Pricing", {"amount": ["4","5","6","3"], "n": ["treinta","cuarenta","cincuenta"]}),
    (1, "Cuando quise cancelar el préstamo hipotecario anticipadamente me cobraron una penalización del {rate}% sobre el capital pendiente que nadie me había explicado al contratar. En letra pequeña de un contrato de {n} páginas. Me costó {amount} euros que no tenía previstos.", "Penalización hipotecaria no informada al contratar descubierta en letra pequeña", "Pricing", {"rate": ["1","1.5","2"], "n": ["cuarenta","cincuenta","sesenta"], "amount": ["3.000","5.000","4.000","2.500"]}),
    (3, "La cuenta de ahorro da un {rate}% de interés anual. Con la inflación actual es perder dinero en términos reales. Hay alternativas en el mercado que ofrecen {rate2}% sin condiciones. Mantener aquí el ahorro es la peor decisión financiera posible.", "Rentabilidad de cuenta ahorro por debajo de inflación y de alternativas del mercado", "Pricing", {"rate": ["0.01","0.02","0.05","0.1"], "rate2": ["3","3.5","4","2.5"]}),
    (4, "La tarjeta de crédito tiene una cuota anual de {amount} euros y los beneficios no justifican ese coste. El cashback es del {rate}% y los seguros de viaje tienen tantas exclusiones que son prácticamente inútiles. Pago por una tarjeta que no me aporta valor real.", "Cuota anual de tarjeta no compensada por los beneficios reales que ofrece", "Pricing", {"amount": ["80","100","120","150"], "rate": ["0.3","0.5","0.2"]}),
    (3, "El tipo de interés del crédito al consumo es del {rate}% TAE para un cliente sin incidencias. La competencia ofrece la mitad. Cuando lo intenté negociar me dijeron que era tarifa fija sin excepciones. Para financiación de consumo este banco no es una opción válida.", "Tipo de interés en crédito al consumo muy elevado sin posibilidad de negociación", "Pricing", {"rate": ["16","17","18","19"]}),
    (2, "Me cobraron {amount} euros por consultar el saldo en un cajero de otra entidad. En la era del banco digital cobrar por consultar tu propio saldo es completamente anacrónico. Además no me lo informaron al contratar la cuenta. Una comisión pequeña pero muy reveladora de la cultura del banco.", "Comisión por consulta de saldo en cajero ajeno anacrónica y no informada al contratar", "Pricing", {"amount": ["0.20","0.30","0.50"]}),
    (4, "El interés de la hipoteca variable que me ofrecieron es Euríbor más {rate}%. Comparado con el mercado actual es bastante caro. Cuando pedí mejora me dijeron que dependía de la vinculación con productos que no necesito. La mejora del precio condiciona a contratar más productos.", "Diferencial hipotecario variable caro condicionado a vinculación de productos no deseados", "Pricing", {"rate": ["1","1.2","1.5","0.9"]}),
    (2, "Las comisiones de gestión del fondo de inversión activo que contraté superan el {rate}% anual. Con esa carga el fondo debe batir al mercado solo para empatar. En la práctica raramente lo consigue. Estoy pagando mucho por un rendimiento que podría obtener gratis con un indexado.", "Comisiones de fondo activo que anulan cualquier posibilidad de rendimiento superior", "Pricing", {"rate": ["1.8","2","2.2","1.5"]}),
    (3, "El depósito a plazo que contraté al {rate}% al vencimiento había aplicado el interés sobre el saldo neto de comisiones de cuenta. La rentabilidad real fue del {rate2}%. Una forma opaca de reducir el tipo efectivo que no se explica en la publicidad del producto.", "Rentabilidad real del depósito reducida por comisiones de cuenta no comunicadas", "Pricing", {"rate": ["3.5","4","3"], "rate2": ["2.8","3.1","2.5"]}),
    # --- TRANSPARENCIA EN PRECIOS ---
    (9, "Todas las comisiones del banco están perfectamente detalladas en un documento de tarifas fácil de encontrar en la web. Sin letra pequeña ni condiciones ocultas. Cuando pregunto me explican el coste exacto antes de hacer cualquier operación. Una transparencia en precios que se agradece.", "Alta transparencia en comunicación de tarifas y precios antes de operar", "Pricing", {}),
    (5, "Las comisiones del banco están en la media del mercado. Ni muy baratas ni muy caras. Los precios están documentados en la web aunque hay que buscarlos un poco. No tengo quejas pero tampoco motivos para recomendarlos especialmente por precio frente a alternativas más económicas.", "Estructura de precios media del mercado sin ventajas ni desventajas competitivas claras", "Pricing", {}),
    (7, "La cuenta sin comisiones tiene condiciones de vinculación alcanzables: nómina superior a {amount} euros o {n} recibos domiciliados. No te exigen ser un gran cliente para acceder a las ventajas. Es una propuesta justa que permite a cualquier cliente evitar las comisiones.", "Condiciones de exención de comisiones alcanzables para el cliente medio", "Pricing", {"amount": ["600","800","1.000","500"], "n": ["tres","cuatro","dos"]}),
    (6, "El tipo de interés de la hipoteca es aceptable aunque no el más bajo del mercado. Lo compensan con menos comisiones de apertura y más flexibilidad en amortizaciones. En el coste total de la hipoteca a largo plazo acaba siendo una opción competitiva si se considera todo.", "Tipo hipotecario compensado por menor coste en comisiones y mayor flexibilidad", "Pricing", {}),
    (8, "Sin cajeros del banco cerca pude usar cualquier cajero de España sin comisión gracias a los acuerdos de la red. Esto es un gran valor cuando viajas por zonas rurales. Sin ese beneficio tendría que buscar cajeros específicos. Un ahorro real en el día a día.", "Sin comisión en cajeros de red ampliada, beneficio tangible en movilidad", "Pricing", {}),
    # --- SEGUROS Y OTROS ---
    (7, "El precio del seguro de coche que contraté a través del banco es {rate}% más barato que la renovación que me daba mi aseguradora anterior. La cobertura es equivalente o mejor. Con la comodidad de tenerlo domiciliado en la misma cuenta. Una compra claramente ganadora en precio.", "Seguro de coche más económico que alternativa previa con cobertura equivalente", "Pricing", {"rate": ["diez","quince","veinte","doce"]}),
    (3, "El seguro de vida vinculado a la hipoteca me cuesta {amount} euros al mes. Comparado con el mismo seguro en una aseguradora externa me cobran el doble. La razón es que el banco tiene margen sobre el seguro vinculado. Un precio abusivo aprovechando la posición de dominio.", "Prima de seguro de vida vinculado a hipoteca muy superior al precio de mercado", "Pricing", {"amount": ["80","100","120","90"]}),
    (9, "Sin cajeros del propio banco en el extranjero puedo sacar efectivo en cualquier cajero de Europa sin comisión gracias a mi tarjeta. En {n} países diferentes nunca he pagado nada extra. Para un viajero frecuente es un beneficio en precios que marca la diferencia.", "Sin comisión por retirada en cajeros europeos para clientes viajeros", "Pricing", {"n": ["cinco","ocho","diez","doce"]}),
]

# =============================================================================
# GENERATE 1000 ROWS
# =============================================================================

# We want 250 per category
category_buckets = {"Productos": [], "Canales": [], "Personal": [], "Pricing": []}
for t in TEMPLATES:
    cat = t[3]
    category_buckets[cat].append(t)

output_rows = []
for cat, bucket in category_buckets.items():
    count = 0
    while count < 250:
        t = random.choice(bucket)
        base_nps, comment_tpl, insight, categoria, variables = t
        # Fill placeholders
        comment = comment_tpl
        for key, options in variables.items():
            placeholder = "{" + key + "}"
            if placeholder in comment:
                comment = comment.replace(placeholder, random.choice(options), 1)
        # Small NPS variation ±1 to add noise, clamped to [1,10]
        nps = max(1, min(10, base_nps + random.choice([-1, 0, 0, 0, 1])))
        output_rows.append([nps, comment, insight, categoria])
        count += 1

random.shuffle(output_rows)

with open("nps_sintetico/feedbacks_2.csv", "w", newline="", encoding="utf-8") as f:
    import csv
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerow(["NPS", "Comentario", "Insight", "Categoria"])
    writer.writerows(output_rows)

print(f"Generated {len(output_rows)} rows")

from collections import Counter
cats = Counter(row[3] for row in output_rows)
print("Category distribution:", dict(cats))
nps_dist = Counter(row[0] for row in output_rows)
print("NPS distribution:", dict(sorted(nps_dist.items())))
